[[DisplayConfig]]
id = 1
model = "GC9A01"
reset_pin = 3
dc_pin = 2
controller_id = 3
chipselect_id = 3
display_size = [240, 240]
inversion = "Normal"
color_order = "Rgb"
orientation.rotation = "Deg0"
orientation.mirrored = false

[[DisplayConfig]]
id = 2
model = "ST7735"
reset_pin = 4
dc_pin = 1
controller_id = 3
chipselect_id = 3
display_size = [240, 240]
inversion = "Normal"
color_order = "Rgb"
orientation.rotation = "Deg0"
orientation.mirrored = false

[[DisplayConfig]]
id = 3
model = "ST7789"
reset_pin = 4
dc_pin = 1
controller_id = 3
chipselect_id = 3
display_size = [240, 240]
inversion = "Normal"
color_order = "Rgb"
orientation.rotation = "Deg0"
orientation.mirrored = false

[[DisplayConfig]]
id = 4
model = "GC9A01"
reset_pin = 4
dc_pin = 1
controller_id = 3
chipselect_id = 3
display_size = [240, 240]
inversion = "Normal"
color_order = "Rgb"
orientation.rotation = "Deg0"
orientation.mirrored = false


[[DisplayConfig]]
id = 5
model = "GC9A01"
reset_pin = 4
dc_pin = 1
controller_id = 3
chipselect_id = 3
display_size = [240, 240]
inversion = "Normal"
color_order = "Rgb"
orientation.rotation = "Deg0"
orientation.mirrored = false
